spring.application.name=growin

spring.config.import=file:env.properties

# Database configurations
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.hikari.schema=${DATABASE_SCHEMA}

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true

jwt.secretKey=${JWT_SECRETKEY}

# Minio Configurations
minio.url=${MINIO_URL}
minio.access.key=${MINIO_ACCESS_KEY}
minio.access.secret=${MINIO_ACCESS_SECRET}
minio.bucket.name=${MINIO_BUCKET_NAME}

spring.servlet.multipart.enabled=true
spring.servlet.multipart.file-size-threshold=100MB
